# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16e5cxHgG5nReF_EK53iKe9N3AMmNjZzW
"""

import random

liczb = random.randint(0, 100,)
print("===Odgadywanie liczb===")

liczba = int(input("Wybierz liczbe z przedzialu od 1 do 100: "))
prob = 1
while liczba != liczb:

    if liczba > liczb:
    	print("Podana liczba jest wieksza od szukanej, sprobuj jeszcze raz")
    elif liczba < liczb:
    	print("Podana liczba jest mniejsza od szukanej, sprobuj jeszcze raz")
    liczba = int(input("Wybierz liczbe z przedzialu od 1 do 100: "))
    prob += 1
print("Gratulacje! Koniec gry, wygrales! Szukana liczba to:", liczb, "Twoja liczba prob to :", prob,)