# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

def string_length(str1):
    count = 0

    for char in str1:
        count += 1

    return count

print(string_length('Patryk'))