# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

str1 = 'https://www.w3resource.com/python-exercises/string'

print(str1.rsplit('/', 1)[0])

print(str1.rsplit('-', 1)[0])