# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

def change_string(str1):
    return str1[-1:] + str1[1:-1] + str1[:1]

print(change_string('Patryk'))
print(change_string('WSB'))