# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

items = input("Input comma-separated sequence of words")

words = [word for word in items.split(",")]

print(",".join(sorted(list(set(words)))))