# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

def odd_values_string(str):
    result = ""

    for i in range(len(str)):
        if i % 2 == 0:
            result = result + str[i]

    return result

print(odd_values_string('Patryk'))
print(odd_values_string('Zielinski'))