# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

def insert_end(str):
    sub_str = str[-2:]

    return sub_str * 4

print(insert_end('Python'))
print(insert_end('Exercises'))