# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

user_input = input("What's your favorite language? ")

print("My favorite language is ", user_input.upper())

print("My favorite language is ", user_input.lower())