# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

def add_tags(tag, word):
    return "<%s>%s</%s>" % (tag, word, tag)

print(add_tags('i', 'Python'))

print(add_tags('b', 'Python Tutorial'))