# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

def reverse_string(str1):
    if len(str1) % 4 == 0:
        return ''.join(reversed(str1))

    return str1

print(reverse_string('abcd'))
print(reverse_string('python'))