# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

def smallest_num_in_list(list):
    min = list[0]
    for a in list:
        if a < min:
            min = a
    return min

print(smallest_num_in_list([1, 2, -8, 0]))