# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

original_list = [10, 22, 44, 23, 4]

new_list = list(original_list)

print(original_list)

print(new_list)