# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

def char_frequency(str1):
    dict = {}

    for n in str1:
        keys = dict.keys()

        if n in keys:
            dict[n] += 1
        else:
            dict[n] = 1

    return dict

print(char_frequency('facebook'))