# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

from random import shuffle

color = ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow']

shuffle(color)

print(color)