# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

num = [7, 8, 120, 25, 44, 20, 27]

num = [x for x in num if x % 2 != 0]

print(num)