# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

def long_words(n, str):
    word_len = []

    txt = str.split(" ")

    for x in txt:
        if len(x) > n:
            word_len.append(x)

    return word_len

print(long_words(3, "The quick brown fox jumps over the lazy dog"))