# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

d = {'x': 10, 'y': 20, 'z': 30}

for dict_key, dict_value in d.items():
    print(dict_key, '->', dict_value)