# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

d = {'Red': 1, 'Green': 2, 'Blue': 3}

for color_key, value in d.items():
    print(color_key, 'corresponds to ', d[color_key])