# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

def change_char(str1):
    char = str1[0]

    str1 = str1.replace(char, '$')

    str1 = char + str1[1:]

    return str1

print(change_char('restart'))