# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

n = int(input("Input a number "))

d = dict()

for x in range(1, n + 1):
    d[x] = x * x

print(d)