# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

d1 = {'a': 100, 'b': 200}

d2 = {'x': 300, 'y': 200}

d = d1.copy()

d.update(d2)

print(d)