# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

myDict = {'a': 1, 'b': 2, 'c': 3, 'd': 4}

print(myDict)

if 'a' in myDict:
    del myDict['a']

print(myDict)