# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

keys = ['red', 'green', 'blue']

values = ['#FF0000', '#008000', '#0000FF']

color_dictionary = dict(zip(keys, values))

print(color_dictionary)