# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

def chars_mix_up(a, b):
    new_a = b[:2] + a[2:]

    new_b = a[:2] + b[2:]

    return new_a + ' ' + new_b

print(chars_mix_up('pat', 'zie'))