# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

for x in range(6):
    if (x == 3 or x == 6):
        continue
    print(x, end=' ')

print("\n")