# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

temp = input("Input the temperature you like to convert? (e.g., 45F, 102C etc.) : ")

degree = int(temp[:-1])

i_convention = temp[-1]

if i_convention.upper() == "C":
    result = int(round((9 * degree) / 5 + 32))
    o_convention = "Fahrenheit"  # Set the output convention as Fahrenheit
elif i_convention.upper() == "F":
    result = int(round((degree - 32) * 5 / 9))
    o_convention = "Celsius"  # Set the output convention as Celsius
else:
    print("Input proper convention.")
    quit()

print("The temperature in", o_convention, "is", result, "degrees.")