# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

import random

target_num, guess_num = random.randint(1, 10), 0

while target_num != guess_num:
    guess_num = int(input('Guess a number between 1 and 10 until you get it right : '))

print('Well guessed!')