# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

lines = []

while True:
    l = input()

    if l:
        lines.append(l.upper())
    else:
        break;

for l in lines:
    print(l)