# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7gFmEwSEc1LmsulWB8wakAX-lEYk0jb
"""

items = []

num = [x for x in input().split(',')]

for p in num:
    x = int(p, 2)

    if not x % 5:
        items.append(p)

print(','.join(items))